version: '3'

services:
  monitoring:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8085:8085"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"